name: CICD Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello World
      run: |
        echo ${{ vars.FOO }}
        echo ${{ secrets.APP_HOST }}
        echo `hostname`
        echo "Hello World"
    - name: Run Python Application
      run: python app.py
    - name: Run Python Application
      run: python hw.py
